name: Build Preview version

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm run vscode:prepublish

      - run: npm install -g vsce

      - run: vsce package --allow-missing-repository --allow-star-activation

      - uses: actions/upload-artifact@v3
        with:
          path: "*.vsix"
